# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8db2f9da7f194205a572e0df0a088c200b9f465886082ceddbd7213d7098945b1f6ce625382f742a70af77d568589ff91e7d2ffca943369135460d5548cdbca5

test:
  secret_key_base: 6884d17b65ecda680ba7599369dcbc9b8fa58e4485db3c47f30123ff00521d4b4a691faa8e83d3a57912920475955c2052584f6e6b4b1132284a8855a4f68f47

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
